locals {
  # Resolve the trust policy template path (custom templates take precedence)
  trust_policy_path = fileexists("${path.module}/trust_policy_templates/custom/${var.trust_policy.policy}.tftpl") ? "${path.module}/trust_policy_templates/custom/${var.trust_policy.policy}.tftpl" : "${path.module}/trust_policy_templates/${var.trust_policy.policy}.tftpl"

  # Load and render the trust policy template
  trust_policy_content = templatefile(
    local.trust_policy_path,
    {
      parameters = var.trust_policy.parameters
    }
  )

  # Extract the trust policy prefix (e.g. "ec2" from "ec2", or "ec2-lambda" from "custom/ec2-lambda")
  trust_policy_prefix = split("/", var.trust_policy.policy)[length(split("/", var.trust_policy.policy)) - 1]

  # Load the default managed policies file
  default_managed_policies = jsondecode(file("${path.module}/identity_policy_templates/default_managed_policies.json"))

  # Resolve the managed policies for the trust policy type in use
  managed_policy_arns = try(local.default_managed_policies[local.trust_policy_prefix], [])

  # Whether the trust policy name contains "ec2" (used to decide on the instance profile)
  # Examples: "ec2", "custom/ec2-lambda", "ec2-something"
  needs_instance_profile = can(regex("ec2", local.trust_policy_prefix))

  # Build a map of inline policies from the identity_policy variable
  # Hash the resources so the key stays stable even if the order changes
  inline_policies = {
    for idx, policy_config in var.identity_policy :
    "${split("/", policy_config.policy)[0]}-${split("/", policy_config.policy)[1]}-${substr(md5(jsonencode(policy_config.resources)), 0, 8)}" => {
      template_path = "${path.module}/identity_policy_templates/${policy_config.policy}.tftpl"
      resources     = policy_config.resources
      parameters    = policy_config.parameters
      service       = split("/", policy_config.policy)[0]
      policy_type   = split("/", policy_config.policy)[1]
    }
  }
}

# IAM Role
resource "aws_iam_role" "this" {
  name                  = var.role_name
  description           = "IAM role generated by the IAM Terraform module."
  assume_role_policy    = local.trust_policy_content
  tags                  = var.tags
  max_session_duration  = 3600
  path                  = var.role_path
  force_detach_policies = true
}

# Inline policies for each entry in identity_policy
resource "aws_iam_role_policy" "inline" {
  for_each = local.inline_policies

  name = "${var.role_name}-${each.value.service}-${each.value.policy_type}"
  role = aws_iam_role.this.id

  policy = jsonencode({
    Version = jsondecode(file(each.value.template_path)).policies.Version
    Statement = [
      for stmt in jsondecode(file(each.value.template_path)).policies.Statement :
      merge(
        {
          Effect = stmt.Effect
          Action = stmt.Action
          Resource = flatten([
            for res in(try(tolist(stmt.Resource), [stmt.Resource])) :
            res == "{{RESOURCE_ARN}}" ? each.value.resources :
            res == "{{RESOURCE_ARN}}/*" ? [for arn in each.value.resources : "${arn}/*"] :
            res == "{{RESOURCE_ARN}}/index/*" ? [for arn in each.value.resources : "${arn}/index/*"] :
            contains(keys(each.value.parameters), replace(replace(res, "{{", ""), "}}", "")) ? [each.value.parameters[replace(replace(res, "{{", ""), "}}", "")]] :
            contains(keys(each.value.parameters), replace(replace(replace(res, "/*", ""), "{{", ""), "}}", "")) ? ["${each.value.parameters[replace(replace(replace(res, "/*", ""), "{{", ""), "}}", "")]}/*"] :
            [res]
          ])
        },
        can(stmt.Sid) && stmt.Sid != null ? { Sid = stmt.Sid } : {}
      )
    ]
  })
}

# Instance profile for EC2 (when the trust policy name contains "ec2")
resource "aws_iam_instance_profile" "this" {
  count = local.needs_instance_profile ? 1 : 0
  name  = var.role_name
  role  = aws_iam_role.this.name
  tags  = var.tags
}

# Default managed policies based on the trust policy type
resource "aws_iam_role_policy_attachment" "managed" {
  for_each = toset(local.managed_policy_arns)

  role       = aws_iam_role.this.name
  policy_arn = each.value
}
